import { z } from "zod";

export const FPS = 30;

export const shotSchema = z.object({
  // Path inside public/. Falls back to the trailer's `source` when omitted.
  src: z.string().optional(),
  // Where in the source clip this shot starts, in seconds.
  startAt: z.number().min(0),
  durationInFrames: z.number().int().positive(),
  // Subtle push-in (1) or pull-out (-1).
  zoom: z.union([z.literal(1), z.literal(-1)]).default(1),
  // Play this shot's own audio (a line of dialogue, in sync).
  voice: z.boolean().default(false),
  voiceGain: z.number().min(0).max(4).default(1),
  caption: z.string().optional(),
  // The drop: white flash and the biggest hit in the score.
  hero: z.boolean().default(false),
});

// A line of dialogue laid over other shots (J-cut / voice-over).
export const voiceoverSchema = z.object({
  from: z.number().int().min(0), // trailer frame where the line starts
  startAt: z.number().min(0), // seconds into the source
  durationInFrames: z.number().int().positive(),
  caption: z.string(),
});

export const trailerSchema = z.object({
  // Main footage file inside public/.
  source: z.string(),
  // Original score inside public/ (generated by scripts/make_score.py).
  score: z.string(),
  showSafeZone: z.boolean(),
  titleText: z.string(),
  endText: z.string(),
  shots: z.array(shotSchema).min(3),
  voiceovers: z.array(voiceoverSchema),
});

export type Shot = z.infer<typeof shotSchema>;
export type Voiceover = z.infer<typeof voiceoverSchema>;
export type TrailerProps = z.infer<typeof trailerSchema>;

export const FOOTAGE = "footage/day-in-the-life.mov";
export const SCORE = "trailer/score.wav";

type Select = {
  at: number;
  frames: number;
  voice?: string;
  // Boost for quieter lines.
  gain?: number;
  hero?: boolean;
};

// Selects from the 12-minute "Day in the Life" footage, in story order.
// `at` is seconds into the footage; `voice` keeps that shot's own audio and
// captions it.
const selects: Select[] = [
  // Cold open, in sync: the intro line under the title.
  {
    at: 1.85,
    frames: 90,
    voice: "Welcome to a day in the life of Mr. Handsome",
  },
  // Morning montage (score only).
  { at: 17.5, frames: 21 }, // brushing teeth
  { at: 131.2, frames: 15 }, // pancake batter
  { at: 164.6, frames: 15 }, // cracking eggs
  { at: 168.3, frames: 12 }, // eggs in the pan
  { at: 175.2, frames: 15 }, // pouring batter
  { at: 216.0, frames: 12 }, // pancake in the pan
  // Car, in sync, straight into the flex.
  {
    at: 503.72,
    frames: 47,
    gain: 1.4,
    voice: "Now it's time to go to the gym and hit upper",
  },
  { at: 505.4, frames: 27 }, // flexing in the car
  // Gym montage: the build, under two voice-over lines.
  { at: 508.2, frames: 18 }, // incline press
  { at: 515.0, frames: 15 }, // row
  { at: 521.0, frames: 15 }, // pulldown
  { at: 534.0, frames: 12 }, // lateral raises
  { at: 540.6, frames: 12 }, // shoulder press
  { at: 558.0, frames: 12 }, // cable triceps
  { at: 574.5, frames: 12 }, // incline curls
  { at: 582.5, frames: 12 }, // preacher curls
  // The drop.
  { at: 588.1, frames: 54, hero: true }, // double-bicep pose
  { at: 602.0, frames: 18 }, // back pose
  // Sign-off, in sync.
  {
    at: 712.75,
    frames: 101,
    gain: 2,
    voice: "That is a full day in the life of Mr. Handsome",
  },
  // End card over the moody gym back shot.
  { at: 545.0, frames: 66 },
];

export const defaultShots: Shot[] = selects.map((s, i) => ({
  startAt: s.at,
  durationInFrames: s.frames,
  zoom: i % 2 === 0 ? 1 : -1,
  voice: Boolean(s.voice),
  voiceGain: s.gain ?? 1,
  caption: s.voice,
  hero: Boolean(s.hero),
}));

export const shotStarts = (shots: Shot[]) =>
  shots.reduce<number[]>(
    (acc, s, i) => [
      ...acc,
      i === 0 ? 0 : acc[i - 1] + shots[i - 1].durationInFrames,
    ],
    [],
  );

const starts = shotStarts(defaultShots);
const flexStart = starts[8];
const heroStart = starts[defaultShots.findIndex((s) => s.hero)];

// Lines from the car monologue, laid over the flex and the gym montage.
export const defaultVoiceovers: Voiceover[] = [
  {
    from: flexStart,
    startAt: 306.42,
    durationInFrames: 70,
    caption: "Because your feelings were never supposed to be your boss",
  },
  {
    // Ends just before the drop, leaving a beat of silence.
    from: heroStart - 9 - 50,
    startAt: 252.33,
    durationInFrames: 50,
    caption: "…because I knew I would never quit.",
  },
];

export const totalDuration = (shots: Shot[]) =>
  shots.reduce((sum, s) => sum + s.durationInFrames, 0);
